/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as BoxRouteImport } from './routes/box'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as SystemSupplyRouteImport } from './routes/system.supply'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSupplyRoute = SystemSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => SystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/culture': typeof CultureRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/seasons': typeof SeasonsRoute
  '/system': typeof SystemRouteWithChildren
  '/system/supply': typeof SystemSupplyRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/culture': typeof CultureRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/seasons': typeof SeasonsRoute
  '/system/supply': typeof SystemSupplyRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/culture': typeof CultureRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/seasons': typeof SeasonsRoute
  '/system': typeof SystemRouteWithChildren
  '/system/supply': typeof SystemSupplyRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/box'
    | '/culture'
    | '/join'
    | '/mission'
    | '/seasons'
    | '/system'
    | '/system/supply'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/box'
    | '/culture'
    | '/join'
    | '/mission'
    | '/seasons'
    | '/system/supply'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/box'
    | '/culture'
    | '/join'
    | '/mission'
    | '/seasons'
    | '/system'
    | '/system/supply'
    | '/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxRoute: typeof BoxRoute
  CultureRoute: typeof CultureRoute
  JoinRoute: typeof JoinRoute
  MissionRoute: typeof MissionRoute
  SeasonsRoute: typeof SeasonsRoute
  SystemRoute: typeof SystemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/supply': {
      id: '/system/supply'
      path: '/supply'
      fullPath: '/system/supply'
      preLoaderRoute: typeof SystemSupplyRouteImport
      parentRoute: typeof SystemRoute
    }
  }
}

interface SystemRouteChildren {
  SystemSupplyRoute: typeof SystemSupplyRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemSupplyRoute: SystemSupplyRoute,
  SystemIndexRoute: SystemIndexRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxRoute: BoxRoute,
  CultureRoute: CultureRoute,
  JoinRoute: JoinRoute,
  MissionRoute: MissionRoute,
  SeasonsRoute: SeasonsRoute,
  SystemRoute: SystemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
