/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoxRouteImport } from './routes/box'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as SurplusRouteImport } from './routes/surplus'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as SystemImpactRouteImport } from './routes/system.impact'
import { Route as SystemKitchenRouteImport } from './routes/system.kitchen'
import { Route as SystemMatchRouteImport } from './routes/system.match'
import { Route as SystemSupplyRouteImport } from './routes/system.supply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SurplusRoute = SurplusRouteImport.update({
  id: '/surplus',
  path: '/surplus',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)
const SystemImpactRoute = SystemImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SystemRoute,
} as any)
const SystemKitchenRoute = SystemKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => SystemRoute,
} as any)
const SystemMatchRoute = SystemMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSupplyRoute = SystemSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => SystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/surplus': typeof SurplusRoute
  '/system': typeof SystemRouteWithChildren
  '/today': typeof TodayRoute
  '/system/impact': typeof SystemImpactRoute
  '/system/kitchen': typeof SystemKitchenRoute
  '/system/match': typeof SystemMatchRoute
  '/system/supply': typeof SystemSupplyRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/surplus': typeof SurplusRoute
  '/today': typeof TodayRoute
  '/system/impact': typeof SystemImpactRoute
  '/system/kitchen': typeof SystemKitchenRoute
  '/system/match': typeof SystemMatchRoute
  '/system/supply': typeof SystemSupplyRoute
  '/system': typeof SystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/surplus': typeof SurplusRoute
  '/system': typeof SystemRouteWithChildren
  '/today': typeof TodayRoute
  '/system/impact': typeof SystemImpactRoute
  '/system/kitchen': typeof SystemKitchenRoute
  '/system/match': typeof SystemMatchRoute
  '/system/supply': typeof SystemSupplyRoute
  '/system/': typeof SystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/box'
    | '/impact'
    | '/join'
    | '/surplus'
    | '/system'
    | '/today'
    | '/system/impact'
    | '/system/kitchen'
    | '/system/match'
    | '/system/supply'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/box'
    | '/impact'
    | '/join'
    | '/surplus'
    | '/today'
    | '/system/impact'
    | '/system/kitchen'
    | '/system/match'
    | '/system/supply'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/box'
    | '/impact'
    | '/join'
    | '/surplus'
    | '/system'
    | '/today'
    | '/system/impact'
    | '/system/kitchen'
    | '/system/match'
    | '/system/supply'
    | '/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxRoute: typeof BoxRoute
  ImpactRoute: typeof ImpactRoute
  JoinRoute: typeof JoinRoute
  SurplusRoute: typeof SurplusRoute
  SystemRoute: typeof SystemRouteWithChildren
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surplus': {
      id: '/surplus'
      path: '/surplus'
      fullPath: '/surplus'
      preLoaderRoute: typeof SurplusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/impact': {
      id: '/system/impact'
      path: '/impact'
      fullPath: '/system/impact'
      preLoaderRoute: typeof SystemImpactRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/kitchen': {
      id: '/system/kitchen'
      path: '/kitchen'
      fullPath: '/system/kitchen'
      preLoaderRoute: typeof SystemKitchenRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/match': {
      id: '/system/match'
      path: '/match'
      fullPath: '/system/match'
      preLoaderRoute: typeof SystemMatchRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/supply': {
      id: '/system/supply'
      path: '/supply'
      fullPath: '/system/supply'
      preLoaderRoute: typeof SystemSupplyRouteImport
      parentRoute: typeof SystemRoute
    }
  }
}

interface SystemRouteChildren {
  SystemImpactRoute: typeof SystemImpactRoute
  SystemKitchenRoute: typeof SystemKitchenRoute
  SystemMatchRoute: typeof SystemMatchRoute
  SystemSupplyRoute: typeof SystemSupplyRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemImpactRoute: SystemImpactRoute,
  SystemKitchenRoute: SystemKitchenRoute,
  SystemMatchRoute: SystemMatchRoute,
  SystemSupplyRoute: SystemSupplyRoute,
  SystemIndexRoute: SystemIndexRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxRoute: BoxRoute,
  ImpactRoute: ImpactRoute,
  JoinRoute: JoinRoute,
  SurplusRoute: SurplusRoute,
  SystemRoute: SystemRouteWithChildren,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
